### ISSUE TITLE
add column for Screen size and resolution

### ISSUE THREAD

**Issue by paulvi** [skypanther/displayclasses#8]
there should be Screen size (in inches) and resolution

data example:

Screen size and resolution 
					iPhone 6 	iPhone 6 Plus 	iPhone 5S 	Galaxy S5
Screen size (inches) 	4.7 	5.5 			4 			5.1
Resolution 			1,334x750 	1,920x1,080 	1,136x640 	1,920x1,080
Pixel density 			326ppi 	401ppi 			326ppi 		432ppi 

taken from http://www.cnet.com/news/screens-test-apple-iphone-6-vs-iphone-6-plus-vs-samsung-galaxy-s5/

**Comment by skypanther** [comment]
This info is essentially what's listed in the platformHeight (or height) and platformWidth (width) columns of the two tables. Where the values don't quite match is for the downsampled screen of the iPhone 6+. Or am I missing something?

**Comment by paulvi** [comment]
well, it was later added within PR #7
